# Generated by Django 4.2.5 on 2023-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweetapp", "0002_tweet_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="time",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
