# Generated by Django 4.2.5 on 2023-09-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweetapp", "0003_alter_tweet_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="time_unix",
            field=models.TimeField(null=True),
        ),
    ]
