# Generated by Django 4.2.5 on 2023-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweetapp", "0004_tweet_time_unix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="time_unix",
            field=models.BigIntegerField(null=True),
        ),
    ]
